import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-background' >
        <div className='w-full h-screen px-8 max-w-2xl m-auto border'>
          {children}
        </div>
      </body>
    </html>
  )
}
